from pydantic import BaseModel, Field
from typing import Optional, Dict, Any, List

class IngestRequest(BaseModel):
    success: Optional[bool] = Field(
        None, 
        description="Whether the original YouTube data extraction request succeeded"
    )
    message: Optional[str] = Field(
        None, 
        description="Status message from the data extraction process"
    )
    data: Optional[Dict[str, Any]] = Field(
        None, 
        description="The primary YouTube video payload object containing metadata, transcript, and comments"
    )
    video_data: Optional[Dict[str, Any]] = Field(
        None, 
        description="Alternative payload parameter key containing the YouTube video details"
    )


class IngestResponse(BaseModel):
    success: bool = Field(
        ..., 
        description="Indicates whether the data ingestion into the vector store was successful"
    )
    message: str = Field(
        ..., 
        description="A friendly status message detailing the ingestion result"
    )
    video_id: str = Field(
        ..., 
        description="The YouTube unique identifier of the video ingested"
    )
    chunks_ingested: int = Field(
        ..., 
        description="The number of parsed document chunks saved into the FAISS vector database"
    )
    collection: str = Field(
        ..., 
        description="The local filesystem path where the FAISS index database files are stored"
    )


class QueryRequest(BaseModel):
    video_id: str = Field(
        ..., 
        description="The YouTube unique identifier of the target video to query"
    )
    question: str = Field(
        ..., 
        description="The natural language question to ask about the video content"
    )


class SourceUsed(BaseModel):
    source: str = Field(
        ..., 
        description="The type of context source used to generate the answer (e.g. transcript, metadata, comments)"
    )
    snippet: str = Field(
        ..., 
        description="The short context text snippet retrieved from the source document"
    )


class QueryResponse(BaseModel):
    success: bool = Field(
        ..., 
        description="Indicates whether the agent query process finished successfully"
    )
    video_id: str = Field(
        ..., 
        description="The YouTube identifier of the video queried"
    )
    question: str = Field(
        ..., 
        description="The query question (potentially rewritten or formatted by the agent)"
    )
    original_question: str = Field(
        ..., 
        description="The original raw question submitted by the user"
    )
    answer: str = Field(
        ..., 
        description="The natural language answer generated by the agent based on video context"
    )
    sources_used: List[SourceUsed] = Field(
        ..., 
        description="The list of context sources and snippets referenced by the agent to construct the answer"
    )
    docs_retrieved: int = Field(
        ..., 
        description="The count of raw chunks retrieved from the FAISS database for processing"
    )


class SessionInfo(BaseModel):
    video_id: str = Field(
        ..., 
        description="The unique identifier of the ingested video session"
    )
    collection: str = Field(
        ..., 
        description="The local directory name storing the session's FAISS index"
    )
    status: str = Field(
        ..., 
        description="The current operational availability status of the session index (e.g. available)"
    )


class SessionsResponse(BaseModel):
    success: bool = Field(
        ..., 
        description="Indicates whether listing the sessions succeeded"
    )
    sessions: List[SessionInfo] = Field(
        ..., 
        description="List of available ingested YouTube video sessions in the local vector store"
    )
    total: int = Field(
        ..., 
        description="The total count of active ingested sessions"
    )


class DeleteSessionResponse(BaseModel):
    success: bool = Field(
        ..., 
        description="Indicates whether the index deletion was successful"
    )
    message: str = Field(
        ..., 
        description="Status message summarizing the deletion result"
    )
